services:
  gitalite:
    image: gitalite
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3003:3003
    network_mode: host
    volumes:
      - /home/callym/.ssh/id_ed25519:/app/id_ed25519
      - /home/callym/.ssh/id_ed25519.pub:/app/id_ed25519.pub
      - ./static/:/app/static
      - ./templates/:/app/templates
      - ./Config.ron:/app/Config.ron
    environment:
      - CONFIG=Config.ron
      - RUST_LOG=off,gitalite=info
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
